Repository AY2223S1-CS2103T-W09-3/tp, pull requests merged in 2022-11, with the labels that each got.

#248 Fix several bugs
  src/main/java/seedu/address/logic/commands/TaskAddCommand.java
  src/main/java/seedu/address/logic/commands/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, v1.4

#240 Make Phone class to follow Singapore phone number and update UG to sh…
  docs/UserGuide.md
  docs/images/JSONSaveFile.png
  docs/team/zicotjia.md
  src/main/java/seedu/address/logic/commands/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/TaskEditCommandParser.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTeamsAddressBook.json
  src/test/java/seedu/address/logic/commands/CreateTeamCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: v1.4

#261 Add test cases for TaskAddCommand
  src/test/java/seedu/address/logic/commands/TaskAddCommandTest.java
Labels: v1.4

#263 Update descriptions of add, edit, and delete features in the User Guide
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/TaskAddCommandTest.java
Labels: DocumentationBug

#264 Update UG with a parameters summary table
  docs/UserGuide.md
Labels: v1.4

#265 Fix Table of Contents in the UG
  docs/UserGuide.md
Labels: v1.4

#266 Modify TeamBuilder to create deep copy and add test cases for modelManager
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
Labels: v1.4
