Repository AY2223S1-CS2103T-W09-3/tp, pull requests merged in 2022-10, with the labels that each got.

#94 V1.2 Implement team skeleton, handling storage of team, add command to add team
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateTeamParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: v1.2

#100 Add TaskAdd command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/TaskAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, v1.2

#113 Add use case 3
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#114 Updated DG with Use Case 4 and 5
  docs/DeveloperGuide.md
Labels: priority.Medium, v1.2

#119 Refactor TaskList class to UniqueTaskList
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
Labels: priority.High, v1.2

#124 Fix bug causing task read from storage to not be added to tasklist
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/team/Team.java
Labels: severity.High, v1.2

#128 Update TaskAddCommand format
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
Labels: priority.Medium, v1.2

#145 V1.2 Fix a bug where editing a person is not reflected on the team's member list
  src/main/java/seedu/address/logic/commands/UnAssignMemberCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/team/Team.java
Labels: severity.High

#146 Create a protected arePrefixedPresents methods for parser
  src/main/java/seedu/address/logic/commands/CreateTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CreateTeamParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskUnmarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnAssignMemberParser.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/team/Team.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#147 Add tracking of task deadlines
  src/main/java/seedu/address/logic/commands/TaskAddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: priority.High, v1.3

#151 Add edit task command
  src/main/java/seedu/address/logic/commands/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TaskEditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.Medium

#152 Edit team command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTeamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task

#157 Bug fix taskbar
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/TaskAddSequenceDiagram.puml
  docs/images/TaskAddSequenceDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, v1.3

#160 Add UML diagrams for create and edit task, update developer guide, reduce unnecessary instantiation of task list and person list of team
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/CreateTeamSequenceDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/CreateTeamSequenceDiagram.png
  docs/images/EditPersonSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/AssignMemberCommand.java
  src/main/java/seedu/address/logic/parser/AssignMemberParser.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High, v1.3

#166 Create team builder and typicalTeams for testing purposes and modified typicalAddressBook
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/team/Team.java
  src/test/data/JsonSerializableAddressBookTest/duplicateTeamAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTeamsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.High

#167 Create TaskBuilder and TypicalTasks for testing purposes
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: v1.3

#178 Add test cases for Team and improve null handling for Team class
  src/main/java/seedu/address/model/team/Name.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/team/NameTest.java
  src/test/java/seedu/address/model/team/TeamTest.java
  src/test/java/seedu/address/model/team/UniqueTeamListTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.High

#186 Change Ui showcase for index.md
  docs/images/Ui.png
Labels: v1.3

#190 Fix a bug that allowed non-empty preambles in some commands
  src/main/java/seedu/address/logic/parser/EditTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskEditCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskUnmarkCommandParser.java
Labels: type.Bug

#234 V1.3 Add test cases for JsonAdaptedTeam and make Date object have a stricter range
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskAddCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/DateOutOfRangeException.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
  src/test/java/seedu/address/logic/parser/TaskAddCommandParserTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/team/TeamTest.java
  src/test/java/seedu/address/model/team/UniqueTeamListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTeamTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.Medium

#235 V1.3 Fix a bug causing NewName to not be optional in TaskEdit Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/TaskEditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug, severity.Low, v1.4
